### ISSUE TITLE
File export when empty

### ISSUE THREAD

**Issue by kapyrna** [sdcervi/DistanceGoals#16]
Downloads a TXT file with only content reading
```null```
No warn message on exporting no contents, no wrapping on the exported TXT file to assist with identification out of context

**Comment by sdcervi** [comment]
Yep still working on this one.  It'll read `null` if empty.

**Comment by sdcervi** [comment]
Wrote some code to disable the Export button if the object is empty. Please test?

**Comment by sdcervi** [comment]
Also, file name is "distance-tracker-data-export.txt" currently. Is that enough context or do I need to add contents to the file itself?
