### ISSUE TITLE
Clear/reset buttons identical redundant

### ISSUE THREAD

**Issue by kapyrna** [sdcervi/DistanceGoals#17]
Blue reset button on top bar and grey clear button on bar below top appear to have identical function

**Comment by sdcervi** [comment]
Good call.  Clear button nukes all localStorage data for this site, Reset button resets to sample data.  Is there a more intuitive way to say that?

**Comment by kapyrna** [comment]
Perhaps "Load defaults" or something indicating it will load whatever demo data is preset to load without local data detected, not sure if it's feasible to dynamically change this button text based on whether the current session has deviated from default state.  "Clear" implies blank at end of action so I think that's fine.

**Comment by sdcervi** [comment]
Ok, I believe I've clarified this some.  Also fixed some minor bugs to hopefully smooth out UX for this feature.
